AWSTemplateFormatVersion: "2010-09-09"
Description: >
  petpics1, 2 and 3
  IAM Role
Parameters:
  AccountToTrust:
    Description: "A4LManagement (General) AccountID"
    Type: String
Resources:
  petpics1:
    Type:  AWS::S3::Bucket
  petpics2:
    Type:  AWS::S3::Bucket
  petpics3:
    Type:  AWS::S3::Bucket
  CrossAccountS3Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
              - !Join ["", ["arn:aws:iam::", !Ref AccountToTrust, ":root"]]
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 's3:ListAllMyBuckets'
                Resource: 'arn:aws:s3:::*'
              - Effect: Allow
                Action: ['s3:ListBucket', 's3:GetBucketLocation']
                Resource: !GetAtt petpics3.Arn
              - Effect: Allow
                Action: ['s3:GetObject', 's3:PutObject']
                Resource: !Join ["", [!GetAtt petpics3.Arn, "/*"]]
Outputs:
  Bucket1URL:
    Value: !Join [ "", [ "https://us-east-1.console.aws.amazon.com/s3/buckets/", !Ref petpics1, "?region=us-east-1&tab=objects" ] ]
  Bucket2URL:
    Value: !Join [ "", [ "https://us-east-1.console.aws.amazon.com/s3/buckets/", !Ref petpics2, "?region=us-east-1&tab=objects" ] ]
  Bucket3URL:
    Value: !Join [ "", [ "https://us-east-1.console.aws.amazon.com/s3/buckets/", !Ref petpics3, "?region=us-east-1&tab=objects" ] ]
  Role:
    Value: !Ref CrossAccountS3Role

